### ISSUE TITLE
static_ adaptor document is not correct 

### ISSUE THREAD

**Issue by jiayuehua** [boostorg/hof#217]
https://www.boost.org/doc/libs/1_76_0/libs/hof/doc/html/include/boost/hof/static.html say that // In C++ this class can't be static-initialized, because of the non-
// trivial default constructor. 
But that's not true. https://godbolt.org/z/46KdEb3r3 .times3 can create without any problem. 
So what is the exactly problem static_ try to solve? Will you give a example that static_ can work but old code can't work. 
Thanks very much.

**Comment by pfultz2** [comment]
Its dynamically initialized not statically initialized.

**Comment by jiayuehua** [comment]
Does that mean static_ is used for constant initialization? https://en.cppreference.com/w/cpp/language/constant_initialization. Here times_function is not pod type, so static_ can be used constant initial it.

**Comment by jiayuehua** [comment]
my bad. I close it.
